name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This will trigger the workflow on every push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the runner to use for the build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # This checks out your code so Dockerfile is available

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Logs into Docker Hub
        with:
          username: ${{ secrets.DOCKER_U }}  # Use the Docker Hub username secret
          password: ${{ secrets.DOCKER_P }}  # Use the Docker Hub password secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for advanced Docker features)

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2  # Builds and pushes the image to Docker Hub
        with:
          context: .  # Path to your Docker context (the current directory)
          push: true  # Pushes the image to Docker Hub
          tags: yourusername/alpine-ssh:latest  # Tag for your Docker image (use your Docker Hub username)
          build-args: |
            PASSWORD=${{ secrets.SSH_PASSWORD }}  # Pass the password to the Dockerfile

      - name: Image Digest
        run: echo "Image pushed with digest ${{ steps.build-push.outputs.digest }}"  # Output the image digest
